name: Frontend CI/CD

on:
  push:
    branches:
      - main          # ← only deploy when merged to main
    paths:
      - 'frontend/**'

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  BUCKET_NAME: bucket_frontend_staticfile_hosting1
  REGION: ${{ secrets.REGION }}
  URL_MAP_NAME: my-balancer

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Build React app
        run: |
          cd frontend
          npm run build

      - name: Upload to GCS bucket
        run: |
          gsutil -m rsync -r -d ./frontend/build \
            gs://${{ env.BUCKET_NAME }}

      - name: Invalidate CDN cache
        run: |
          gcloud compute url-maps invalidate-cdn-cache \
            ${{ env.URL_MAP_NAME }} \
            --path "/*" \
            --project=${{ env.PROJECT_ID }}


#